
import React, { useState, useEffect } from 'react';
import QRCode from 'qrcode';

interface ToolProps {
  slug: string;
  onSuccess: (msg: string) => void;
  onError: (msg: string) => void;
}

const GeneralTools: React.FC<ToolProps> = ({ slug, onSuccess, onError }) => {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [qrUrl, setQrUrl] = useState('');
  const [loading, setLoading] = useState(false);

  // Auto-run logic for tools like Password Generator
  useEffect(() => {
    if (slug === 'password-generator') {
      handleProcess();
    }
  }, [slug]);

  const handleProcess = async () => {
    setLoading(true);
    try {
      let result = '';
      
      switch (slug) {
        case 'json-formatter':
          result = JSON.stringify(JSON.parse(input), null, 4);
          break;
        case 'base64-encoder':
          result = btoa(input);
          break;
        case 'base64-decoder':
          result = atob(input);
          break;
        case 'html-minifier':
          result = input.replace(/\n/g, '').replace(/\s\s+/g, ' ');
          break;
        case 'lorem-ipsum-generator':
          const words = "lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat".split(" ");
          result = Array.from({ length: 50 }).map(() => words[Math.floor(Math.random() * words.length)]).join(" ") + ".";
          break;
        case 'password-generator':
          const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+";
          result = Array.from({ length: 16 }).map(() => charset[Math.floor(Math.random() * charset.length)]).join("");
          break;
        case 'qr-code-generator':
          if (!input) throw new Error("URL/Text required");
          const url = await QRCode.toDataURL(input, { width: 512, margin: 2 });
          setQrUrl(url);
          onSuccess("QR Code Generated");
          setLoading(false);
          return;
        case 'word-counter':
          const wordCount = input.trim().split(/\s+/).filter(Boolean).length;
          const charCount = input.length;
          result = `Words: ${wordCount}\nCharacters: ${charCount}\nSentences: ${input.split(/[.!?]+/).length - 1}`;
          break;
        case 'case-converter':
          result = input.toUpperCase(); // Default to upper if just clicking run
          break;
        case 'meta-tag-generator':
          result = `<title>${input}</title>\n<meta name="description" content="Generated by ToolVerse">\n<meta name="viewport" content="width=device-width, initial-scale=1">`;
          break;
        default:
          result = input.split('').reverse().join('');
      }

      setOutput(result);
      if (slug !== 'password-generator' || input) {
        onSuccess("Processing Complete");
      }
    } catch (err) {
      onError("Processing failed. Please check input format.");
    }
    setLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(output || qrUrl);
    onSuccess("Copied to clipboard!");
  };

  return (
    <div className="space-y-10 animate-in fade-in duration-500">
      <div className="flex justify-between items-center px-2">
         <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Client-Side Engine v1.0</span>
         <button onClick={() => { setInput(''); setOutput(''); setQrUrl(''); }} className="text-red-500 font-bold text-[10px] uppercase tracking-tighter">Reset Engine</button>
      </div>

      {slug !== 'password-generator' && slug !== 'lorem-ipsum-generator' && (
        <textarea 
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder={slug === 'qr-code-generator' ? "Enter URL or text..." : "Paste your input here..."}
          className="w-full h-64 p-8 rounded-[2.5rem] border border-slate-200 focus:ring-8 focus:ring-indigo-500/5 outline-none font-mono text-sm bg-slate-50 shadow-inner transition-all"
        />
      )}

      <div className="flex flex-col sm:flex-row gap-4">
        <button 
          onClick={handleProcess} 
          disabled={loading}
          className="flex-grow py-6 bg-indigo-600 text-white rounded-2xl font-black text-lg shadow-xl hover:bg-indigo-700 transition-all active:scale-95 disabled:opacity-50"
        >
          {loading ? "Computing..." : slug === 'password-generator' ? "Generate New Password" : "Run Tool Engine"}
        </button>
        {(output || qrUrl) && (
          <button onClick={handleCopy} className="py-6 px-10 bg-slate-900 text-white rounded-2xl font-black text-lg shadow-xl hover:bg-slate-800 transition-all">
            Copy Result
          </button>
        )}
      </div>

      {qrUrl && (
        <div className="flex flex-col items-center justify-center p-12 bg-white rounded-[3rem] border border-slate-100 shadow-2xl animate-in zoom-in-95">
          <img src={qrUrl} alt="QR Code" className="w-64 h-64 md:w-80 md:h-80 rounded-2xl border-8 border-white shadow-lg" />
          <a href={qrUrl} download="toolverse_qr.png" className="mt-8 text-indigo-600 font-bold hover:underline uppercase text-xs tracking-widest">Download PNG</a>
        </div>
      )}

      {output && (
        <div className="relative group animate-in slide-in-from-top-4">
          <div className="absolute top-6 right-6 opacity-0 group-hover:opacity-100 transition-opacity">
            <span className="px-3 py-1 bg-emerald-500 text-white text-[9px] font-black uppercase rounded-full shadow-lg">Output Ready</span>
          </div>
          <textarea 
            readOnly 
            value={output}
            className="w-full h-64 p-8 rounded-[2.5rem] border border-emerald-100 bg-emerald-50/20 font-mono text-sm text-slate-700 outline-none shadow-sm"
          />
        </div>
      )}

      {/* Case Converter Specific Buttons */}
      {slug === 'case-converter' && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <button onClick={() => setOutput(input.toUpperCase())} className="p-4 bg-white border border-slate-200 rounded-xl font-bold text-[10px] uppercase hover:bg-slate-50 transition-all">UPPERCASE</button>
          <button onClick={() => setOutput(input.toLowerCase())} className="p-4 bg-white border border-slate-200 rounded-xl font-bold text-[10px] uppercase hover:bg-slate-50 transition-all">lowercase</button>
          <button onClick={() => setOutput(input.replace(/\b\w/g, l => l.toUpperCase()))} className="p-4 bg-white border border-slate-200 rounded-xl font-bold text-[10px] uppercase hover:bg-slate-50 transition-all">Title Case</button>
          <button onClick={() => setOutput(input.charAt(0).toUpperCase() + input.slice(1).toLowerCase())} className="p-4 bg-white border border-slate-200 rounded-xl font-bold text-[10px] uppercase hover:bg-slate-50 transition-all">Sentence</button>
        </div>
      )}
    </div>
  );
};

export default GeneralTools;
