
/**
 * ToolVerse Edge Client v1.0
 * Handles the communication between React frontend and Cloudflare Edge.
 */

export interface ToolResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}

export const executeOnEdge = async (toolId: string, category: string, input: any): Promise<ToolResponse> => {
  try {
    // Check for Pro Token in LocalStorage
    const proToken = localStorage.getItem('tv_pro_token');
    
    const response = await fetch("/api/execute", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(proToken ? { "Authorization": `Bearer ${proToken}` } : {})
      },
      body: JSON.stringify({
        toolId,
        category,
        input,
        // Send Ad Proof if generated by a rewarded ad component
        adProof: sessionStorage.getItem('tv_ad_proof') || null
      }),
    });

    const result = await response.json();

    if (!response.ok || !result.success) {
      return { 
        success: false, 
        error: result.error || "Edge Engine: Command failed." 
      };
    }

    return { 
      success: true, 
      data: result.data 
    };
  } catch (err: any) {
    return { 
      success: false, 
      error: "Connection lost: ToolVerse Edge Core is currently unreachable." 
    };
  }
};
