
import React from 'react';
import SEOHead from '../components/SEOHead';

const Terms: React.FC = () => {
  return (
    <div className="max-w-7xl mx-auto px-4 py-16 md:py-24 sm:px-6 lg:px-8">
      <SEOHead 
        title="Terms and Conditions" 
        description="Standard terms of service for ToolVerse users." 
        url="https://toolverse-4gr.pages.dev/terms" 
      />

      <div className="max-w-3xl mx-auto bg-white p-10 md:p-16 rounded-[3rem] border border-slate-100 shadow-sm">
        <h1 className="text-4xl font-black text-slate-900 mb-10 tracking-tight">Terms and Conditions</h1>
        
        <div className="prose prose-slate prose-sm md:prose-base max-w-none space-y-8 text-slate-600 font-medium leading-relaxed">
          <p>By accessing and using this website, you agree to the following terms and conditions.</p>

          <section>
            <h2 className="text-lg font-black text-slate-900 uppercase tracking-widest mb-4">Usage</h2>
            <p>All tools provided on this website are free to use for general informational and utility purposes only.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-slate-900 uppercase tracking-widest mb-4">No Warranty</h2>
            <p>We do not guarantee the accuracy, reliability, or completeness of any output generated by our tools. Use them at your own risk.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-slate-900 uppercase tracking-widest mb-4">Prohibited Use</h2>
            <p>You agree not to misuse the website for illegal activities, automated abuse, or attempts to disrupt services.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-slate-900 uppercase tracking-widest mb-4">Intellectual Property</h2>
            <p>All website content, design, and tools are owned by this website unless otherwise stated.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-slate-900 uppercase tracking-widest mb-4">Changes</h2>
            <p>We reserve the right to modify or discontinue any part of the website without notice.</p>
          </section>

          <section>
            <h2 className="text-lg font-black text-slate-900 uppercase tracking-widest mb-4">Contact</h2>
            <p>If you have questions about these terms, please contact us through the contact page.</p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
